### ISSUE TITLE
Docker Container Permission Issue: Temporary Workaround for Running app_chat.py Locally

### ISSUE THREAD

**Issue by mariogarcia-ar** [lexatlas-org/lexatlas-semantic-kernel#2]
**Description:**

We’ve identified a permission issue that affects the ability to run `app_chat.py` inside the Docker container as expected. Until this is resolved, we recommend using a local virtual environment (venv) to run the application directly from your machine.

---

### ✅ Temporary Workaround

You can run `app_chat.py` locally by following these steps:

#### 1. Set up a virtual environment

```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
pip install -r requirements.txt
```

#### 2. Configure environment variables

Create a `.env` file in your project root and define the required variables, including:

- **🔗 `DATABASE_URL`**  
  Chainlit requires a PostgreSQL connection. Install PostgreSQL locally:

  - macOS: `brew install postgresql`
  - Ubuntu: `sudo apt install postgresql`
  - Windows: [https://www.postgresql.org/download/](https://www.postgresql.org/download/)

  Example connection string:

  ```env
  DATABASE_URL=postgresql://postgres:postgres@localhost:5432/lexatlas
  ```

- **🔐 `LITERAL_API_KEY`**  
  Obtain your API key from [https://app.chainlit.io/](https://app.chainlit.io) and add it to your `.env`:

  ```env
  LITERAL_API_KEY=your_chainlit_api_key
  ```

> Ensure your `.env` also includes other required keys such as `OPENAI_API_KEY`, Azure service credentials, etc.

#### 3. Run the application

```bash
chainlit run app_chat.py --host 0.0.0.0 --port 8000
```

Access it at [http://localhost:8000/](http://localhost:8000)

---

### 🐳 Docker Compose Option

The application can also be run via Docker Compose using `app_chat.py`. Ensure the following:

#### 1. Dockerfile includes:

```dockerfile
COPY app.py app_chat.py kernel.py .env /app/
ENV CHAINLIT_APP=app_chat.py
CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0", "--port", "8000"]
```

#### 2. docker-compose.yml includes:

```yaml
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CHAINLIT_APP=app_chat.py
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
      - AZURE_AI_AGENT_PROJECT_CONNECTION_STRING=${AZURE_AI_AGENT_PROJECT_CONNECTION_STRING}
      - AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME=${AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME}
      - PROJECT_CONNECTION_STRING=${PROJECT_CONNECTION_STRING}
    depends_on:
      - db
```

#### 3. Run the stack:

```bash
docker-compose up --build
```

This will launch `app_chat.py` at [http://localhost:4000/](http://localhost:4000)

---

### 📌 Use Cases

This setup is particularly useful for:

- Testing multi-agent conversational flows
- Exploring plugin/tool integration
- Running functional evaluations with real or simulated input
